apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: seldon-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.7.0
